### ISSUE TITLE
Cloud Router release rpm should not modify /etc/issue

### ISSUE THREAD

**Issue by abn** [iixlabs/cloudrouter#13]
The rpm currently does:
```sh
sed -i 's/Fedora/CloudRouter 1.0 Beta based on Fedora/' /etc/issue
```

This is not always the ideal behaviour. This should be only done in CloudRouter spins.

**Comment by abn** [comment]
@dfj build script has been modified. We need to also modify the rpm specfile.

**Comment by dfj** [comment]
@abn please review the PR and close this issue if you merge it.

**Comment by abn** [comment]
Changes verified. Closing.
